#!/usr/bin/env python3
"""Check Agda, normalize its executable conversion, and check the Lean endpoint.

This is a small data exporter, not a general translation of Agda proofs to Lean.
Agda checks the abstract equivalence and transport law. Lean independently checks
the exported formula and the concrete positive-real instance.
"""
import argparse
import json
from pathlib import Path
import re
import shutil
import sys
import tempfile

from common import ROOT, DEPENDENCIES, CACHE, RESULTS, CUBICAL_COMMIT, audit, check_lean, demand, digest

TARGET = ROOT / "theorems/generated/Conversion.lean"
SNAPSHOT = DEPENDENCIES / "wire.json"


def extract(log):
    forms = []
    for line in log.splitlines():
        line = line.removeprefix("JSON> ").strip()
        if not line.startswith("{"):
            continue
        event = json.loads(line)
        info = event.get("info", {})
        if event.get("kind") == "Error" or info.get("kind") == "Error":
            raise ValueError("Agda normalization failed")
        if info.get("kind") == "AllGoalsWarnings" and any(
                info.get(key) for key in ("errors", "visibleGoals", "invisibleGoals")):
            raise ValueError("Agda left errors or unsolved goals")
        if info.get("kind") == "NormalForm":
            forms.append(info["expr"])
    if len(forms) != 1:
        raise ValueError("Expected exactly one normalized wire")
    text = forms[0].replace("Agda.Builtin.List.List.", "")
    # Accept only a fully parenthesized natural-number list, never source code.
    tokens = re.findall(r"\d+|∷|\[\]|[()]", text)
    if re.sub(r"\d+|∷|\[\]|[()]|\s+", "", text):
        raise ValueError("Unexpected wire syntax")
    position = 0

    def parse_list():
        nonlocal position
        if position >= len(tokens):
            raise ValueError("Truncated wire list")
        token = tokens[position]
        position += 1
        if token == "(":
            values = parse_list()
            if position >= len(tokens) or tokens[position] != ")":
                raise ValueError("Unbalanced wire list")
            position += 1
            return values
        if token == "[]":
            return []
        if not token.isdecimal() or position >= len(tokens) or tokens[position] != "∷":
            raise ValueError("Expected a natural-number cons")
        position += 1
        return [int(token)] + parse_list()

    values = parse_list()
    if position != len(tokens):
        raise ValueError("Trailing wire syntax")
    return values


def render(words, source_hash):
    if len(words) > 64 or words[:2] != [20261003, 1]:
        raise ValueError("Unsupported conversion interface")
    if any(type(word) is not int or word < 0 for word in words):
        raise ValueError("Expected natural-number wire data")
    position = 2

    def expression(expected):
        nonlocal position
        if position >= len(words):
            raise ValueError("Truncated expression")
        tag = words[position]
        position += 1
        if tag == 0:
            result, kind = "x.1", "Scalar"
        elif tag == 1:
            result, kind = "x.2", "Unit"
        elif tag == 2:
            result, kind = f"(scale {expression('Scalar')} {expression('Unit')})", "Scalar"
        elif tag == 3:
            result, kind = f"(reciprocal {expression('Unit')})", "Unit"
        else:
            raise ValueError("Unknown expression tag")
        if kind != expected:
            raise ValueError("Expression type mismatch")
        return result

    left, right = expression("Scalar"), expression("Unit")
    if position != len(words):
        raise ValueError("Trailing conversion data")
    return f'''-- Generated by dependencies/bridge.py from Agda's normalized executable body.
-- Agda source SHA-256: {source_hash}
namespace powerlib.generated

def convert {{Scalar Unit : Type}} (scale : Scalar → Unit → Scalar)
    (reciprocal : Unit → Unit) (x : Scalar × Unit) : Scalar × Unit :=
  ({left}, {right})

-- The independent endpoint contract is checked by the Lean kernel.
theorem convert_spec {{Scalar Unit : Type}} (scale : Scalar → Unit → Scalar)
    (reciprocal : Unit → Unit) (x : Scalar × Unit) :
    convert scale reciprocal x = (scale x.1 (reciprocal x.2), reciprocal x.2) := rfl

end powerlib.generated
'''


def rebuild(write=False):
    agda = CACHE / "agda"
    if demand([agda, "--numeric-version"]).strip() != "2.8.0":
        raise RuntimeError("Expected Agda 2.8.0; run dependencies/setup.py")
    cubical = CACHE / "cubical"
    if demand(["git", "-C", cubical, "rev-parse", "HEAD"]).strip() != CUBICAL_COMMIT:
        raise RuntimeError("Cubical commit mismatch")
    if demand(["git", "-C", cubical, "status", "--porcelain", "--untracked-files=all"]).strip():
        raise RuntimeError("Cubical checkout must be clean")
    with tempfile.TemporaryDirectory(prefix="powerlib-bridge-") as directory:
        stage = Path(directory)
        (stage / "theorems").mkdir()
        shutil.copy(ROOT / "theorems/Conversion.agda", stage / "theorems/Conversion.agda")
        shutil.copy(ROOT / "powerlib.agda-lib", stage)
        libraries = stage / "libraries"
        libraries.write_text(str(cubical / "cubical.agda-lib") + "\n")
        entry = stage / "theorems/Conversion.agda"
        flags = [agda, f"--library-file={libraries}", "--no-default-libraries"]
        log = demand(flags + [entry], cwd=stage)
        path = json.dumps(str(entry))
        commands = (f'IOTCM {path} None Direct (Cmd_load {path} [])\n'
                    f'IOTCM {path} None Direct (Cmd_compute_toplevel DefaultCompute "wire")\n')
        normalized = demand(flags + ["--interaction-json", "--interaction-exit-on-error"],
                            input=commands, cwd=stage)
        words = extract(normalized)
        content = render(words, digest(entry))
        candidate = stage / "Conversion.lean"
        candidate.write_text("import Lean\n" + content +
                             audit(["powerlib.generated.convert_spec"], include_core=False))
        check_lean(candidate)
        snapshot = json.dumps(words) + "\n"
        if write:
            TARGET.write_text(content)
            SNAPSHOT.write_text(snapshot)
        elif TARGET.read_text() != content or SNAPSHOT.read_text() != snapshot:
            raise RuntimeError("Generated conversion is stale; run python3 dependencies/bridge.py --write")
        report = {"agda": "2.8.0", "cubical_commit": CUBICAL_COMMIT,
                  "agda_source_sha256": digest(entry), "wire": words,
                  "generated_sha256": digest(TARGET), "status": "AGDA_AND_LEAN_CHECKED"}
        RESULTS.mkdir(exist_ok=True)
        (RESULTS / "bridge.log").write_text(log + normalized)
        (RESULTS / "bridge.json").write_text(json.dumps(report, indent=2) + "\n")
    return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Publish checked generated files")
    args = parser.parse_args()
    try:
        print(json.dumps(rebuild(args.write), indent=2))
    except (ValueError, RuntimeError, OSError) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
